# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: )
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
Boardgame.create(title: "test", description: "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy! ", price_per_day: "10")
